FROM decidim/decidim:0.7.2
MAINTAINER info@codegram.com

ENV RAILS_ENV production

COPY Gemfile .
COPY Gemfile.lock .
RUN bundle install
COPY . .
RUN bundle exec rake assets:precompile
CMD bundle exec passenger start -p ${PORT:-3000} --max-pool-size ${WEB_CONCURRENCY:-5}
