:concurrency: 5
:queues:
- default
- mailers
- newsletter
- events
- metrics
- exports
- translations
- close_meeting_reminder
- conference_diplomas
- newsletters_opt_in
- reminders
- user_report
- vote_reminder
- block_user
- delete_inactive_participants
